### ISSUE TITLE
The offset is invalid and cannot be updated

### ISSUE THREAD

**Issue by xuhaoa** [mralinp/KhiarWare#1]
In the update on May 29th, the offset has been invalid. The attempt to update the offset failed to work. Is it invalid? Great project, already star.

**Comment by xuhaoa** [comment]
For those who forget to change the keys and default no hacks

**Comment by mralinp** [comment]
Hi, maybe sth is wrong with your modifications, I'll update offsets right now and it's working perfectly for me, can you tell me what did you exactly do for updating the offsets?

**Comment by mralinp** [comment]
I'll add an auto-update script to solve the issue, as well.
Thanks for your notice.

**Comment by piwawa** [comment]
> I'll add an auto-update script to solve the issue, as well.
> Thanks for your notice.

How to run this auto-update script? Sorry i am newbie.

**Comment by mralinp** [comment]
just follow the steps in README.md. install python 3.6 or above, install `requests` python library, using `python-pip`, then run the updater. (`python updater.py`)
