### ISSUE TITLE
The code can't be complied!

### ISSUE THREAD

**Issue by piwawa** [mralinp/KhiarWare#2]
![1](https://user-images.githubusercontent.com/46926496/83775822-fa7edc80-a6b9-11ea-9da6-1caa1e3c322d.png)
Some Identifiers are not declared
"signatures": not class or namespace name

**Comment by mralinp** [comment]
Hi, I think that you might have forgotten to include, `Offsets.h` file into the project.
The signatures namespace is defined there.

**Comment by piwawa** [comment]
> Hi, I think that you might have forgotten to include, `Offsets.h` file into the project.
> The signatures namespace is defined there.

You can see all the head file in right, obviously Offset.h is included.
